name: football_stats
description: A comprehensive football statistics application with real-time data and analytics.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  google_sign_in: ^6.1.6
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Theming
  material_color_utilities: ^0.8.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Data & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # HTTP & Networking
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  dartz: ^0.10.1
  
  # UI Components
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  url_launcher: ^6.2.2
  table_calendar: ^3.0.9
  
  # Development
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  
  # Assets
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"